data:
  dataset: ISIC2018
  root_path: /mnt/home/hdc/data/public_data/ISIC2018
  crop_size: 320
  in_chns: 3

train:
  num_classes: 2
  base_lr: 0.01
  batch_size: 12
  epochs: 150

semi:
  conf_thresh: 0.95
  ema_decay: 0.99
  consistency_type: mse
  consistency: 0.1
  consistency_rampup: 200.0