data:
  dataset: KvasirSEG
  root_path: /mnt/home/hdc/data/public_data/Kvasir-SEG
  crop_size: 320
  in_chns: 3

train:
  num_classes: 2
  base_lr: 0.01
  batch_size: 24 # 32
  epochs: 200

semi:
  conf_thresh: 0.95
  ema_decay: 0.99
  consistency_type: mse
  consistency: 0.1
  consistency_rampup: 200.0